title: Mi Página de GitHub Personalizada
email: mgonz370@itam.mx
description: >- # esta descripción aparecerá debajo de tu título.
  Esta es una descripción detallada de mi página personal de GitHub, creada con Jekyll.
baseurl: "" # si tu sitio está en un subdirectorio, como /blog
url: "https://monica637.github.io" # tu URL de GitHub Pages
twitter_username: # Aquí podrías dejarlo vacío, ya que no tienes Twitter.
github_username: monica637

